model_opts:
  model: SFRNN
  obs_input_type: [local_box, pose, local_surround, speed, box]
  apply_class_weights: True
  normalize_boxes: True
  enlarge_ratio: 1.5
  obs_length: 16
  time_to_event: [30, 60]
  overlap: 0.6
  dataset: pie
net_opts:
  regularization_value: 0.0001
exp_opts:
  num_hidden_units: [256, 512]
  datasets: [pie, pie, pie]
  batch_size: [10, 10, 10]
  epochs: [100, 100, 100]
  lr: [0.00005, 0.0001, 0.0005]
